apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleaning-impact-results
  namespace: pjung
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: shared
