apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleaning-impact-data
  namespace: pjung
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: shared
