experiments:
- dataset: hospital
  scenarios:
  - name: original
    versions:
    - ''
  memory: 256Gi
image:
  repository: larmor27/hc36
  tag: latest
postgres:
  image: postgres:11
  user: holocleanuser
  password: abcd1234
  database: holo
volumes:
  dataPVC: cleaning-impact-data
  dataMountPath: /home/data
  resultsPVC: cleaning-impact-results
  resultsMountPath: /home/results
