apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleaning-impact-data-renuver
  namespace: pjung
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: shared
