version: '3.8'

services:
  postgres:
    image: postgres:11
    container_name: pghc
    environment:
      POSTGRES_DB: holo
      POSTGRES_USER: holocleanuser
      POSTGRES_PASSWORD: abcd1234
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    image: hc36:latest
    container_name: hc36
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: holo
      DATABASE_USER: holocleanuser
      DATABASE_PASSWORD: abcd1234
      DATASET: hospital_ear_realistic
      RUNS: 10
    networks:
      - app-network
    working_dir: /home/experiments
    command: ["./entrypoint.sh"]
    platform: linux/amd64
    volumes:
      - /Users/philipp/code/error-paper/benchmarks/holoclean/results:/home/results  # Mount the /home/results directory to a local folder named "results"
      - /Users/philipp/code/error-paper/benchmarks/holoclean/testdata:/home/testdata

networks:
  app-network:
    driver: bridge

